#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os

from setuptools import setup, find_packages

this_directory = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(this_directory, "README.md")) as file:
    long_description = file.read()

setup(
    name="onetask",
    version="0.2.6",
    author="onetask",
    author_email="info@onetask.ai",
    description="Official Python SDK for the onetask API",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/onetask-ai/onetask-python",
    keywords=["onetask", "machine learning", "supervised learning", "python"],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
    ],
    package_dir={"": "."},
    packages=find_packages("."),
    install_requires=[
        "appnope==0.1.2",
        "argcomplete==1.12.3",
        "argon2-cffi==21.1.0",
        "attrs==21.2.0",
        "backcall==0.2.0",
        "bertopic==0.9.3",
        "bleach==4.1.0",
        "certifi==2021.10.8",
        "cffi==1.15.0",
        "charset-normalizer==2.0.7",
        "click==8.0.3",
        "Cython==0.29.24",
        "debugpy==1.5.1",
        "decorator==5.1.0",
        "defusedxml==0.7.1",
        "entrypoints==0.3",
        "filelock==3.4.0",
        "hdbscan==0.8.27",
        "huggingface-hub==0.1.2",
        "idna==3.3",
        "importlib-metadata==4.8.2",
        "importlib-resources==5.4.0",
        "jedi==0.18.0",
        "Jinja2==3.0.3",
        "joblib==1.1.0",
        "jsonschema==4.2.1",
        "llvmlite==0.37.0",
        "MarkupSafe==2.0.1",
        "matplotlib-inline==0.1.3",
        "mistune==0.8.4",
        "mypy-extensions==0.4.3",
        "nbclient==0.5.8",
        "nbconvert==6.3.0",
        "nbformat==5.1.3",
        "nest-asyncio==1.5.1",
        "nltk==3.6.5",
        "notebook==6.4.5",
        "numba==0.54.1",
        "numpy==1.20.3",
        "packaging==21.2",
        "pandas==1.3.4",
        "pandocfilters==1.5.0",
        "parso==0.8.2",
        "pathspec==0.9.0",
        "pexpect==4.8.0",
        "pickleshare==0.7.5",
        "Pillow==8.4.0",
        "platformdirs==2.4.0",
        "plotly==4.14.2",
        "prometheus-client==0.12.0",
        "prompt-toolkit==3.0.22",
        "ptyprocess==0.7.0",
        "pycparser==2.21",
        "Pygments==2.10.0",
        "pynndescent==0.5.5",
        "pyparsing==2.4.7",
        "pyrsistent==0.18.0",
        "python-dateutil==2.8.2",
        "pytz==2021.3",
        "PyYAML==5.4.1",
        "pyzmq==22.3.0",
        "qtconsole==5.2.0",
        "QtPy==1.11.2",
        "regex==2021.11.10",
        "requests==2.26.0",
        "retrying==1.3.3",
        "sacremoses==0.0.46",
        "scikit-learn==1.0.1",
        "scipy==1.7.2",
        "Send2Trash==1.8.0",
        "sentence-transformers==2.1.0",
        "sentencepiece==0.1.96",
        "six==1.16.0",
        "terminado==0.12.1",
        "testpath==0.5.0",
        "threadpoolctl==3.0.0",
        "tokenizers==0.10.3",
        "tomli==1.2.2",
        "torch==1.10.0",
        "torchvision==0.11.1",
        "tornado==6.1",
        "tqdm==4.62.3",
        "traitlets==5.1.1",
        "transformers==4.12.4",
        "typed-ast==1.5.0",
        "typing-extensions==4.0.0",
        "umap-learn==0.5.2",
        "urllib3==1.26.7",
        "wasabi==0.8.2",
        "wcwidth==0.2.5",
        "webencodings==0.5.1",
        "widgetsnbextension==3.5.2",
        "zipp==3.6.0",
    ],
)
